"""Explicit local opt-in for the registered isolated Staging app; never Production."""
import argparse
from pathlib import Path
import plistlib

ROOT = Path(__file__).resolve().parents[1]
HOST = 'station-cat-music-r2.yehao1105.workers.dev'
TEAM = '2AM5S7BM2N'
BUNDLE = 'org.stationcat.music.staging'

def configure(root):
    config = root / 'Config'
    entitlements = {'com.apple.developer.associated-domains': ['applinks:' + HOST, 'webcredentials:' + HOST]}
    (config / 'R2.local.entitlements').write_bytes(plistlib.dumps(entitlements))
    # Empty expansion prevents xcconfig from treating the second slash as a comment.
    (config / 'R2.local.xcconfig').write_text(f'''// Generated by scripts/configure_r2.py; Staging only.
STATION_NATIVE_AUTH_ENABLED = YES
STATION_NATIVE_MUSIC_ENABLED = YES
STATION_PERSONAL_SYNC_ENABLED = YES
STATION_NATIVE_AUTH_ORIGIN = https:/$()/{HOST}
STATION_MUSIC_WEB_ORIGIN = https:/$()/{HOST}
STATION_APP_ENTITLEMENTS = Config/R2.local.entitlements
''')

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--enable', action='store_true', required=True)
    parser.parse_args()
    configure(ROOT)
    print(f'Staging local opt-in prepared: {TEAM}.{BUNDLE} at {HOST}. Other configurations unchanged.')
